.TH Z 1 "2020-08-19" "z 1.0.0" "z"
.nh
.SH NAME
z - navigate faster by learning your habits
.SH SYNOPSIS
\fBz\fP [\fBoptions\fP] \fIsearch\fP...
.SH DESCRIPTION
.B z
learns where you spend time and makes it easier to get there.
.SH OPTIONS
.SS Alternative behavior
These options replace the standard behavior of \fBz\fP.
.TP
\fB\-f\fP, \fB\-\-forget\fP
Forget the path found by \fIsearch\fP.
.TP
\fB\-\-add\fP
Add \fIsearch\fP to the database.
.SH EXIT STATUS
The \fBz\fP utility exits 0 on success or 1 on errors.
