.TH ZSQL 1 "2020-08-19" "zsql 1.0.0" "zsql"
.nh
.SH NAME
zsql - navigate faster by learning your habits
.SH SYNOPSIS
\fBzsql\fP [\fBoptions\fP] \fIsearch\fP...
.SH DESCRIPTION
.B zsql
learns where you spend time and makes it easier to get there.
.SH OPTIONS
.SS Alternative behavior
These options replace the standard behavior of \fBzsql\fP.
.TP
\fB\-f\fP, \fB\-\-forget\fP
Forget the path found by \fIsearch\fP.
.TP
\fB\-\-add\fP
Add \fIsearch\fP to the database.
.SH EXIT STATUS
The \fBzsql\fP utility exits 0 on success or 1 on errors.
