version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Checkout submodules"
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: "Build"
          command: |
            autoreconf --install
            ./configure
            make distcheck

workflows:
  build:
    jobs:
      - build
