version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            git clone --branch v2.6.1 https://github.com/JuliaStrings/utf8proc
            cd utf8proc
            make && sudo make install
      - run:
          name: "Build"
          command: |
            autoreconf --install
            ./configure
            make -j3 distcheck

workflows:
  build:
    jobs:
      - build
